makefile(
   subdirs: [
	     'CSPOutput'
	     'Compiler'
	     'Extras'
	     'Grammars'
	     'Oracles'
	     'Outputs'
	     'OutputManager'
	     'PrincipleManager'
	     'PrincipleWriter'
	     'SXDG'
	     'Solver'
	     'XTAG'
	     'scripts'
	    ]
   
   lib: [
	 'Helpers.ozf'
	 
	 'xdk.ozf'
	 'xdkc.ozf'
	 'xdkconv.ozf'
	 'xdks.ozf'

	 'ul.el'
	 'xdag.sty'

	 '4712.ulsocket'
	 '4712.txt'

	 'testnodesetserver.oz'
	 'ReifiedIncludeTest.oz'
	 
	 'tack-iozsef-1.1.pkg'
	 'tack-TkTreeWidget-0.7.pkg'

	 'Licence_CeCILL_V2-en.txt'

	 %%

% 	 'Outputs/Lib/AllDags.ozf'
% 	 'Outputs/Lib/AllDags1.ozf'
% 	 'Outputs/Lib/AllDags2.ozf'
% 	 'Outputs/Lib/AllDags3.ozf'
% 	 'Outputs/Lib/CLLS.ozf'
% 	 'Outputs/Lib/CLLS1.ozf'
% 	 'Outputs/Lib/Dag.ozf'
% 	 'Outputs/Lib/Dag1.ozf'
% 	 'Outputs/Lib/Dag2.ozf'
% 	 'Outputs/Lib/Dag3.ozf'
% 	 'Outputs/Lib/Dags.ozf'
% 	 'Outputs/Lib/Dags1.ozf'
% 	 'Outputs/Lib/Dags2.ozf'
% 	 'Outputs/Lib/Dags3.ozf'
% 	 'Outputs/Lib/Decode.ozf'
% 	 'Outputs/Lib/Latex.ozf'
% 	 'Outputs/Lib/Latex1.ozf'
% 	 'Outputs/Lib/Latex2.ozf'
% 	 'Outputs/Lib/Latex3.ozf'
% 	 'Outputs/Lib/Latexs.ozf'
% 	 'Outputs/Lib/Latexs1.ozf'
% 	 'Outputs/Lib/Latexs2.ozf'
% 	 'Outputs/Lib/Latexs3.ozf'
% 	 'Outputs/Lib/Pretty.ozf'
% 	 'Outputs/Lib/Pretty1.ozf'
% 	 'Outputs/Lib/XML.ozf'
% 	 'Outputs/Lib/XML1.ozf'
% 	 'Outputs/Lib/XML2.ozf'
% 	 'Outputs/Lib/XML3.ozf'
% 	 'Outputs/Lib/XML4.ozf'
% 	 'Outputs/Lib/XTAGDerivation.ozf'
	 
% 	 'Solver/Principles/Lib/TestPW.ozf'
% 	 'Solver/Principles/Lib/Agr.ozf'
% 	 'Solver/Principles/Lib/AgrPW.ozf'
% 	 'Solver/Principles/Lib/Agreement.ozf'
% 	 'Solver/Principles/Lib/AgreementDissPW.ozf'
% 	 'Solver/Principles/Lib/AgreementPW.ozf'
% 	 'Solver/Principles/Lib/AgreementSubset.ozf'
% 	 'Solver/Principles/Lib/AgreementSubsetDiplomPW.ozf'
% 	 'Solver/Principles/Lib/Barriers.ozf'
% 	 'Solver/Principles/Lib/BarriersAttrib.ozf'
% 	 'Solver/Principles/Lib/BarriersLabels.ozf'
% 	 'Solver/Principles/Lib/BarriersPW.ozf'
% 	 'Solver/Principles/Lib/BarsPW.ozf'
% 	 'Solver/Principles/Lib/BlockPW.ozf'
% 	 'Solver/Principles/Lib/CSD.ozf'
% 	 'Solver/Principles/Lib/CatPW.ozf'
% 	 'Solver/Principles/Lib/Chorus.ozf'
% 	 'Solver/Principles/Lib/Climbing.ozf'
% 	 'Solver/Principles/Lib/ClimbingPW.ozf'
% 	 'Solver/Principles/Lib/ClimbingSubgraphsPW.ozf'
% 	 'Solver/Principles/Lib/Coindex.ozf'
% 	 'Solver/Principles/Lib/CoindexEdge.ozf'
% 	 'Solver/Principles/Lib/CommasPW.ozf'
% 	 'Solver/Principles/Lib/CsdPW.ozf'
% 	 'Solver/Principles/Lib/Customs.ozf'
% 	 'Solver/Principles/Lib/Dag.ozf'
% 	 'Solver/Principles/Lib/DagPW.ozf'
% 	 'Solver/Principles/Lib/DisjointDaughtersPW.ozf'
% 	 'Solver/Principles/Lib/DominancePW.ozf'
% 	 'Solver/Principles/Lib/Dutch.ozf'
% 	 'Solver/Principles/Lib/Entries.ozf'
% 	 'Solver/Principles/Lib/Government.ozf'
% 	 'Solver/Principles/Lib/Government1PW.ozf'
% 	 'Solver/Principles/Lib/GovernmentAcl01PW.ozf'
% 	 'Solver/Principles/Lib/GovernmentDiplomPW.ozf'
% 	 'Solver/Principles/Lib/GovernmentDissPW.ozf'
% 	 'Solver/Principles/Lib/GraphConditions.ozf'
% 	 'Solver/Principles/Lib/GraphConditions1.ozf'
% 	 'Solver/Principles/Lib/GraphDist.ozf'
% 	 'Solver/Principles/Lib/GraphMakeEdges.ozf'
% 	 'Solver/Principles/Lib/GraphMakeEdges1.ozf'
% 	 'Solver/Principles/Lib/GraphMakeNodes.ozf'
% 	 'Solver/Principles/Lib/GraphMakeNodes1.ozf'
% 	 'Solver/Principles/Lib/GraphPWConstraints.ozf'
% 	 'Solver/Principles/Lib/GraphPWDist.ozf'
% 	 'Solver/Principles/Lib/In.ozf'
% 	 'Solver/Principles/Lib/In1.ozf'
% 	 'Solver/Principles/Lib/LcfgPW.ozf'
% 	 'Solver/Principles/Lib/Linking12BelowStartEnd.ozf'
% 	 'Solver/Principles/Lib/LinkingAbove.ozf'
% 	 'Solver/Principles/Lib/LinkingAboveBelow1or2Start.ozf'
% 	 'Solver/Principles/Lib/LinkingAboveBelow1or2StartPW.ozf'
% 	 'Solver/Principles/Lib/LinkingAboveEnd.ozf'
% 	 'Solver/Principles/Lib/LinkingAboveEndPW.ozf'
% 	 'Solver/Principles/Lib/LinkingAboveStart.ozf'
% 	 'Solver/Principles/Lib/LinkingAboveStartEnd.ozf'
% 	 'Solver/Principles/Lib/LinkingBelow.ozf'
% 	 'Solver/Principles/Lib/LinkingBelow1or2Start.ozf'
% 	 'Solver/Principles/Lib/LinkingBelow1or2StartPW.ozf'
% 	 'Solver/Principles/Lib/LinkingBelowEnd.ozf'
% 	 'Solver/Principles/Lib/LinkingBelowEndPW.ozf'
% 	 'Solver/Principles/Lib/LinkingBelowStart.ozf'
% 	 'Solver/Principles/Lib/LinkingBelowStartEnd.ozf'
% 	 'Solver/Principles/Lib/LinkingBelowStartPW.ozf'
% 	 'Solver/Principles/Lib/LinkingDaughter.ozf'
% 	 'Solver/Principles/Lib/LinkingDaughterEnd.ozf'
% 	 'Solver/Principles/Lib/LinkingDaughterEndDissPW.ozf'
% 	 'Solver/Principles/Lib/LinkingDaughterEndPW.ozf'
% 	 'Solver/Principles/Lib/LinkingEnd.ozf'
% 	 'Solver/Principles/Lib/LinkingEndDissPW.ozf'
% 	 'Solver/Principles/Lib/LinkingEndPW.ozf'
% 	 'Solver/Principles/Lib/LinkingMother.ozf'
% 	 'Solver/Principles/Lib/LinkingMotherEnd.ozf'
% 	 'Solver/Principles/Lib/LinkingMotherPW.ozf'
% 	 'Solver/Principles/Lib/LinkingNotDaughter.ozf'
% 	 'Solver/Principles/Lib/LinkingNotMother.ozf'
% 	 'Solver/Principles/Lib/LinkingSisters.ozf'
% 	 'Solver/Principles/Lib/LockingDaughters.ozf'
% 	 'Solver/Principles/Lib/LockingDaughtersDissIDPAPW.ozf'
% 	 'Solver/Principles/Lib/LockingDaughtersDissPAPW.ozf'
% 	 'Solver/Principles/Lib/LookRight.ozf'
% 	 'Solver/Principles/Lib/Order1Conditions.ozf'
% 	 'Solver/Principles/Lib/Order2Conditions.ozf'
% 	 'Solver/Principles/Lib/Order2MakeNodes.ozf'
% 	 'Solver/Principles/Lib/OrderBlocksPW.ozf'
% 	 'Solver/Principles/Lib/OrderConditions.ozf'
% 	 'Solver/Principles/Lib/OrderDepsPW.ozf'
% 	 'Solver/Principles/Lib/OrderDist.ozf'
% 	 'Solver/Principles/Lib/OrderMakeNodes.ozf'
% 	 'Solver/Principles/Lib/OrderPW.ozf'
% 	 'Solver/Principles/Lib/OrderWithCutsConditions.ozf'
% 	 'Solver/Principles/Lib/OrderWithCutsDist.ozf'
% 	 'Solver/Principles/Lib/OrderWithCutsMakeNodes.ozf'
% 	 'Solver/Principles/Lib/Out.ozf'
% 	 'Solver/Principles/Lib/PAgrPW.ozf'
% 	 'Solver/Principles/Lib/PGovernmentDissPW.ozf'
% 	 'Solver/Principles/Lib/PL.ozf'
% 	 'Solver/Principles/Lib/PartialAgreement.ozf'
% 	 'Solver/Principles/Lib/PartialAgreementDissPW.ozf'
% 	 'Solver/Principles/Lib/PlPW.ozf'
% 	 'Solver/Principles/Lib/Projectivity.ozf'
% 	 'Solver/Principles/Lib/ProjectivityPW.ozf'
% 	 'Solver/Principles/Lib/Relative.ozf'
% 	 'Solver/Principles/Lib/SameEdges.ozf'
% 	 'Solver/Principles/Lib/ScopePW.ozf'
% 	 'Solver/Principles/Lib/Subgraphs.ozf'
% 	 'Solver/Principles/Lib/SubgraphsDissPW.ozf'
% 	 'Solver/Principles/Lib/SubgraphsPW.ozf'
% 	 'Solver/Principles/Lib/TAGConditions.ozf'
% 	 'Solver/Principles/Lib/TAGDist.ozf'
% 	 'Solver/Principles/Lib/TAGMakeNodes.ozf'
% 	 'Solver/Principles/Lib/Test.ozf'
% 	 'Solver/Principles/Lib/TreeConditions.ozf'
% 	 'Solver/Principles/Lib/TreeMakeNodes.ozf'
% 	 'Solver/Principles/Lib/TreePW.ozf'
% 	 'Solver/Principles/Lib/ValencyPW.ozf'
% 	 'Solver/Principles/Lib/XTAG.ozf'
% 	 'Solver/Principles/Lib/XTAGLinking.ozf'
% 	 'Solver/Principles/Lib/XTAGRedundant.ozf'
% 	 'Solver/Principles/Lib/XTAGRoot.ozf'
	]
   
   bin: [
	 'xdk.exe'
	 'xdkc.exe'
	 'xdkconv.exe'
	 'xdks.exe'
	]

   doc: [
	 'index.html'
	 'pslab.css'
	 'xdk.gif'
	]

   clean: [".#*" "*~" "#*#" "*.ozf" "*.exe" "*.o" "*.so-*" "*.slp*"]

   author: ['mogul:/debusmann/ralph' 'mogul:/duchier/denys']
   blurb: 'XDG Development Kit (XDK)'
   mogul: 'mogul:/debusmann/xdk/'
   uri: 'x-ozlib://debusmann/xdk/'
   version: '1.8.1'
   info_html: '<p>This is the XDK, the development kit for Extensible Dependency Grammar (XDG). It is the successor of the <a href="http://www.mozart-oz.org/mogul/info/duchier/coli/dg.html">TDG parser and grammar development environment</a>.<p>You can find information about XDG <a href="http://www.ps.uni-sb.de/~rade/xdg.html">here/a>.'
   )
