#!/bin/bash
cp Solver/Principles/Lib/Opti_off.oz Solver/Principles/Lib/Opti.oz
cp Solver/Principles/Lib/Opti_off.ozf Solver/Principles/Lib/Opti.ozf
echo "The native IsIn optimization is now turned off."
