#!/usr/bin/perl
$file = @ARGV[0];
open(fh,$file);
@lines = <fh>;
close(fh);

$lines = "";
foreach $line (@lines) {
    $lines = "$lines$line";
}

$_ = $lines;

s/\x7b/\\textttAAA\\AAABBB/g;
s/\x7d/\\textttAAA\\BBBBBB/g;
s/<([\?!][a-zA-Z]*)/<\\textcolor{MyDarkPurple}{\1}/g;
s/<([a-zA-Z]*)([ >])/<\\textcolor{MyDarkBlue}{\1}\2/g;
s/<\/([a-zA-Z]*)>/<\\textcolor{MyDarkBlue}{\/\1}>/g;
s/\x27([^\x27]*)\x27/\\textcolor{MyDarkOrange}{\x27\1\x27}/g;
s/\x22([^\x22]*)\x22/\\textcolor{MyDarkOrange}{\x22\1\x22}/g;
s/\t/        /g;
s/AAA/{/g;
s/BBB/}/g;

$lines = $_;

open(fh,">$file.tex");
print fh $lines;
close(fh);
